Add permanent redirect from HTTP to HTTPS
saygoweb/ansible-role-apache pull request #10
Opened 2019-04-04 10:00 UTC by irahopkinson

Configure permanent redirect from HTTP to HTTPS.

2019-04-20 03:46 UTC, cambell-prince requested changes
Thanks @irahopkinson Main comment is about the meaningful white space (which is annoying for sure).  Otherwise fine.  Thanks for the PR.

2019-04-20 03:46 UTC, cambell-prince commented on templates/vhost_proxypath_ssl.conf.j2
>  {% endif %}
The layout here, and throughout the file, is intentional.  This isn't code, the white space is important outside of the {% %} scope.  Your change would force a blank line between the ServerName and ServerAlias directives.  No harm, but not typically done in most Apache config files.

I suggest keeping the formatting as it was for this reason.

2019-04-20 03:46 UTC, cambell-prince commented on templates/vhost_proxypath_ssl.conf.j2
> +    ServerAdmin {{ item.server_admin }}
Formatting as above.

2019-04-20 03:46 UTC, cambell-prince commented on templates/vhost_proxypath_ssl.conf.j2
> +    SSLCertificateChainFile {{host.ssl_path | default(apache_ssl_path)}}/{{ host.chain_file }}
Formatting as above

2019-04-20 03:46 UTC, cambell-prince commented on templates/vhost_proxypath_ssl.conf.j2
> +    {% if host.extra is defined %}
I think its better to have the template directives start in column 0.  Its not code, and as above white space outside of {% %} matters.

2019-04-22 03:32 UTC, irahopkinson commented
Ha, for the first three VSCode was being more helpful with the file layout than I wanted it to be. I've also removed the indents.

2019-04-22 11:30 UTC, merged